### ISSUE TITLE
Кастомные патчвады

### ISSUE THREAD

**Issue by Timurue** [Vlad-Tarabukin/better-hlm-editor#5]
В релизе 0.2.1 написано что поддержка кастомных патчвадов есть, но как их добавить я так и не понял

**Comment by Vlad-Tarabukin** [comment]
Они добавляются через папку mods в папке уровня. Если такой папки нет, то ее надо добавить самому. В ближайшем релизе сделаю так, чтобы папка mods добавлялась автоматически
